### ISSUE TITLE
Unassign Skill Points button crashes every time

### ISSUE THREAD

**Issue by zizibaloob** [ChaosMarc/PlugY#25] opened 2020-11-01 02:39 UTC
Windows 10
Diablo 2 LoD 1.14d
PlugY 12.00

I've only tried it three times, but every time I press the button to unassign all of my skill points, the game crashes. Playing a Sorc in A1 Normal right now if that matters.

    [SKILLS POINTS]
    ActiveSkillsUnassignment=1
    ActiveSkillsUnassignmentOneByOne=0

**Comment by lishaoxia1985** [comment] 2020-11-01 03:20
this branch has a bug, you can use this:
https://github.com/haxifix/PlugY

**Comment by zizibaloob** [comment] 2020-11-01 03:53
Are there any compatibility issues to be aware of when switching between implementations of PlugY?

**Comment by ChaosMarc** [comment] 2020-11-01 22:50
There shouldn't be any complications. Also I will look into this. Must be a merge conflict.

**Comment by markm11** [comment] 2020-11-02 08:45
I have tested this and do not have any problems.  Did you create a new character or did this character come from a lower Diablo version?

**Comment by ChaosMarc** [comment] 2020-11-02 08:52
I can reproduce it with 1.14d (all other versions still work fine). the problem does not occur with the pre-build dll that is available in haxifix' repository. but if I build it from his sources the bug occurs too. I feel the creeping dread that he forgot to check in some changes

**Comment by markm11** [comment] 2020-11-02 09:00
I have forked your sources and updated mine to yours when you applied halifax's code. When I build it. I still do not see that problem.

**Comment by ChaosMarc** [comment] 2020-11-02 09:11
could you upload the plugy.dll you built?

**Comment by markm11** [comment] 2020-11-02 09:33
You could get it from the installer I created here.  https://github.com/markm11/PlugY/blob/master/PlugYInstaller/PlugY_The_Survival_Kit_v12.00.exe
Just know this has changes to where the plugy.ini lives.   It has to reside in where the plugy.dll lives.   This was a fix I put in for D2Modmaker.   I am using Visual Studio 2017.

**Comment by ChaosMarc** [comment] 2020-11-02 09:41
I will try compiling it with VS2017.

I like the changes in your repository (based on the commit messages). perhaps you could create a PR with some documentation of what was changed exactly?

**Comment by markm11** [comment] 2020-11-02 19:52
My Windows is 8.1 Enterprise.  I am testing it with 1.14d.   I see that zizibaloob is on Windows 10.   Is that what your are on?

**Comment by ChaosMarc** [comment] 2020-11-02 20:25
Windows 10 as well. I will try the crashing builds on win 8.1 tomorrow. 
For now I tried to debug the problem. the crash occurs in SkillsPoints.cpp:71. ptSkill->ptNextSkill is NULL for the last skill in the loop. if I choose ignore the ingame error (with a debug build, or while debugging) the unassignment process is successful. But I have no clue what this means :D seems fine to me, as the last skill in a list wouldn't have a nextSkill ptr. but the code worked before, so it shouldn't be a problem...

**Comment by ChaosMarc** [comment] 2020-11-02 21:22
tested it. for me the game crashes on win8.1 enterprise as well

**Comment by markm11** [comment] 2020-11-02 21:35
Just tried my installer on Windows 10 with a brand new Diablo 2 install.  Upgraded D2 to 1.14d.   Copied over one of my characters and still could not get it to crash.   Also installed Visual Studio 19 and rebuilt the code and again no crash.   Sorry I cannot help out with not duplicating this bug.

**Comment by lishaoxia1985** [comment] 2020-11-03 00:28
@ChaosMarc Maybe you compiler setting has some problem, I'm not sure.

**Comment by markm11** [comment] 2020-11-03 07:04
I feel embarrassed.  For some reason I was thinking stats not skills.  Once I saw where you were in the code I realized my mistake.
I can reproduce this bug.   That part of the code causing the problem is a call to this function "D2AddPlayerStat( ptChar, STATS_NEWSKILLS, nbPoints, 0 );"  Line 72 in SkillPoints.cpp.  I will keep looking into this.   Forgive me for my stupidly.

**Comment by markm11** [comment] 2020-11-03 07:43
After looking into it more I believe that problems is with this code.
FCT_ASM(D2SetSkillBaseLevelOnClient_114)
PUSH EBX
PUSH EBX
PUSH ESI
PUSH DWORD PTR SS : [ESP + 0x14]
PUSH DWORD PTR SS : [ESP + 0x14]
MOV EBX, DWORD PTR SS : [ESP + 0x14]
MOV EAX, ECX
MOV ESI, EDX
CALL V2SetSkillBaseLevelOnClient
POP ESI
POP EBX
RETN 0xC
}}

It is changing the pointer value of "ptChar".

**Comment by markm11** [comment] 2020-11-03 08:00
@ChaosMarc  when debugging the code you can actually turn off the debug error so you can continue with debugging.

**Comment by ChaosMarc** [comment] 2020-11-03 08:15
@markm11 that's really great news. Don't worry about the misunderstanding. I'm just happy that you found the bug for yourself :)

yeah I found out that you could just debug over it too. the respec itself works fine. the error message says something about "the value of esp was not properly saved across a function call". google let me to this answer which seems helpful (for someone knowing what he does ^^): https://stackoverflow.com/a/1332874

If you haven't seen it: @haxifix must have had the same problem as he created this commit: https://github.com/haxifix/PlugY/commit/58549561ab4d8e52ad32be83357e4da87beed652 "Fix skill respec". But I have the feeling that he just forgot to commit one of his changes.

**Comment by markm11** [comment] 2020-11-03 08:25
I looked at his code and it is already in my code.   I will keep looking at it.

**Comment by ChaosMarc** [comment] 2020-11-09 08:32
fixed by https://github.com/ChaosMarc/PlugY/pull/30 
many thanks to you @markm11

**Closed by ChaosMarc** 2020-11-09 08:32 UTC
Labels: bug
